### ISSUE TITLE
Dragged item disappears on scroll up/down

### ISSUE THREAD

**Issue by xiom84** [samuelarbibe/dnd-timeline#41]
Hi,

when i drag an item and scroll down or up the dragged item disappears when the movement is larger than the timeline height. 

<img width="640" alt="image" src="https://github.com/samuelarbibe/dnd-timeline/assets/2255128/a5568580-dc3d-4958-86a4-58bcc3339b07">

**Comment by samuelarbibe** [comment]
Hey, on what exact example are you experiencing it? And are you using virtualization?

**Comment by xiom84** [comment]
For example here: https://www.dnd-timeline.com/

**Comment by samuelarbibe** [comment]
Ok, so here is the deal:  
When using tanstack/virtual, only rows that are in the visible area are rendered.  
This means, that when an item is dragged from a visible row, and that row becomes invisible because of scrolling, that row will unmount and the item itself will unmount as well.  
  
The solution comes from @tanstack/virtual:  
https://tanstack.com/virtual/latest/docs/api/virtualizer#rangeextractor  
You can help the library understand which rows should and shouldn't be rendered by using the `rangeExtractor` props, and make sure the library never unmounts a row whose item is currently being dragged.  
  
Anyway, I will make sure to implement this fix in the example and demo page ASAP, and update you.

**Comment by xiom84** [comment]
Sounds fantastatic

Thanks for the incredible fast solution.

**Comment by samuelarbibe** [comment]
Fixed! the demo page will be fixed as well soon.  
Check out the code for the "virtual" example, it should help you.  
  
https://dnd-timeline-virtual.vercel.app

**Comment by xiom84** [comment]
Perfect thanks, that helps a lot.
